apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: exoplanet-demo
    name: exoplanet-demo
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: exoplanet-demo
        tier: backend
    spec:
      containers:
        - env:
            - name: LOG_LEVEL
              value: debug
          image: exoplanet-demo:7fgae7d
          name: exoplanet-demo
          ports:
            - containerPort: 8000
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /app
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /app
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 256m
              memory: 256Mi